### ISSUE TITLE
"ValueError: zero length field name in format" during installation

### ISSUE THREAD

**Issue by sergani** [AGProjects/python-application#2]
Hi, 

I'm installing on Centos 6.8, with python2.6. I'm getting the following error when installing using pip or from source:
```python
Traceback (most recent call last):
  File "setup.py", line 6, in <module>
    from application import __info__ as package_info
  File "/root/python-application-master/application/__init__.py", line 4, in <module>
    from application.__info__ import __project__, __summary__, __webpage__, __version__, __author__, __email__, __license__, __copyright__
  File "/root/python-application-master/application/__info__.py", line 14, in <module>
    __copyright__ = "Copyright 2006-2016 {}".format(__author__)
ValueError: zero length field name in format
```

Any thoughts? 

Thanks
//M

**Comment by sergani** [comment]
Edited the __info__.py file manually to bypass ..

**Comment by saghul** [comment]
Note that Python 2.6 is not supported, so you are on your own...
